プロトタイプ 投稿機能
jin5211/Nagomi_170c pull request #14
Opened 2024-04-17 12:43 UTC by ootakito

# What
ビューデータの部分テンプレートを弄ってました。
# Why
ビューデータを完成させる為

2024-04-17 13:56 UTC, Takenoko463 requested changes
form部分テンプレートに渡している変数について

2024-04-17 13:56 UTC, Takenoko463 commented on app/views/prototypes/_form.html.erb
> +<%= form_with model: @prototype, local: true do |f|%>
@ootakito 

prototypes/newビューから_form部分プレートに渡した変数はなんでしょうか

2024-04-18 00:30 UTC, zinkoko-lab commented on app/controllers/prototypes_controller.rb
> +    params.require(:prototype).permitted(:title, :catch_copy, :concept)
permitted を permit に訂正してください。

2024-04-18 05:16 UTC, Takenoko463 commented on app/views/prototypes/_form.html.erb
> +<%= form_with model: @prototype, local: true do |f|%>
https://master.tech-camp.in/v2/curriculums/8076
カリキュラム

2024-04-18 05:30 UTC, Takenoko463 commented
以下の動画追加が必要
- 必要な情報を適切に入力して「保存する」ボタンを押すと、プロトタイプ情報がデータベースに保存される動画
- 入力に問題がある状態で「保存する」ボタンが押された場合、情報は保存されず、そのページに留まる動画

2024-04-18 05:50 UTC, jin5211 commented
LGTM!

2024-04-18 05:51 UTC, merged